ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[[getting-started]]
== Getting Started

=== Setting Up A Project

Just add impl module to classpath and run test either from an IDE or Maven.

[source,xml,subs="+attributes"]
----
<dependency>
    <groupId>org.jboss.arquillian.extension</groupId>
    <artifactId>arquillian-warp</artifactId>
    <version>{version_project}</version>
    <type>pom</type>
</dependency>
----

or any framework-specific extension:

[source,xml,subs="+attributes"]
----
<dependency>
    <groupId>org.jboss.arquillian.extension</groupId>
    <artifactId>arquillian-warp-jsf</artifactId>
    <version>{version_project}</version>
</dependency>
----

Use the servlet protocol in `arquillian.xml` configuration:

[source,xml]
----
<defaultProtocol type="Servlet 3.0"/>
----

=== Writing Warp Tests

To allow your test to use the Warp, place a `@WarpTest` annotation on the test class:

[source,java]
----
@RunWith(Arquillian.class)
@WarpTest
@RunAsClient
public class BasicTest {
}
----

CAUTION: Don't forget to force Arquillian to run the test on a client with a
`@RunAsClient` annotation.

==== Using `Warp` To Trigger The Client Action

You can use any HTTP client, such as WebDriver (driven by
http://arquillian.org/arquillian-extension-drone[`@Drone`]), to trigger
the server logic:

[source,java]
----
@Drone
WebDriver browser;
----

Then use `Warp` utility class to run `initiate` method.

[source,java]
----
@Test
public void test() {

    Warp
       .initiate(new Activity() {

            public void perform() {
                browser.navigate().to(contextPath + "index.jsf");
            }})

       .inspect(new Inspection() {
            private static final long serialVersionUID = 1L;
        });
}
----

You need to provide `Activity` - the contract of this interface is that
its `perform` method leads to triggering one or more HTTP requests
against `contextPath` URL (injected by Arquillian).

Finally, in the `inspect` method, you need to provide object which
implements `Inspection` interface. This interface provides contract for
object which can execute server-side logic.

CAUTION: Don't forget to provide `serialVersionUID` for `Inspection` objects.

==== Asserting Server State With `Inspection`

In the `Inspection` implementation, you can provide test methods
annotated with lifecycle-test annotations:

* `@BeforeServlet`
* `@AfterServlet`
* `@BeforePhase`
* `@AfterPhase`

Simple assertion may look like:

[source,java]
----
new Inspection() {

    private static final long serialVersionUID = 1L;

    @Inject
    CDIBean cdiBean;

    @AfterPhase(RENDER_RESPONSE)
    public void test_initial_state() {
        assertEquals("John", cdiBean.getName());
    }
}
----

NOTE:  You can use dependency injection to bring the classes such as
CDI beans, EJB beans, or any other resource supported by Arquillian.
